server:
  port : 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: 'classpath:data/schema.sql'
      data-locations: 'classpath:data/data.sql'